### ISSUE TITLE
the trait `std::error::Error` is not implemented for `binary_serde::DeserializeError`

### ISSUE THREAD

**Issue by oroulet** [roeeshoshani/binary_serde#5]
even with std feature enabled, I still get that error if trying to use `?`  to convert DeserializeError to Std::error::Error. Wasn't it exactly what that feature should enabled?

**Comment by roeeshoshani** [comment]
Hi, what version of this crate are you using?

If you are using the latest version, please provide me with more information about what you are trying to do, for example sharing a code sample that doesn't work, so that i can further look into the issue.

As far as i know, the `std` feature works properly on the most recent version of the crate and allows converting a `DeserializeError` to an `std::error::Error`.

For example, using crate version `1.0.22`, which is the latest as of writing this message, the following code compiles just fine:
```rust
fn foo() -> Result<(), Box<dyn std::error::Error>> {
    let _ = Bla::binary_deserialize(&[0], binary_serde::Endianness::Little)?;
    Ok(())
}

#[derive(Debug, BinarySerde)]
struct Bla {
    a: u8,
}
```
